/* minimum glibc 2.4; modification time of buildlist 1255544480 */
__asm__(".symver __readlinkat_chk, __readlinkat_chk@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_rth_add, inet6_rth_add@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_rth_space, inet6_rth_space@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_set_val, inet6_opt_set_val@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_append, inet6_opt_append@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_find, inet6_opt_find@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_finish, inet6_opt_finish@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver splice, splice@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_next, inet6_opt_next@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_rth_init, inet6_rth_init@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_rth_segments, inet6_rth_segments@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_get_val, inet6_opt_get_val@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver tee, tee@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver GLIBC_2.5, GLIBC_2.5@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_rth_getaddr, inet6_rth_getaddr@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_opt_init, inet6_opt_init@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver vmsplice, vmsplice@GLIBC_DONT_USE_THIS_VERSION_2.5");
__asm__(".symver inet6_rth_reverse, inet6_rth_reverse@GLIBC_DONT_USE_THIS_VERSION_2.5");
