# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target boost_date_time-static
ADD_LIBRARY(boost_date_time-static STATIC IMPORTED)

# Create imported target boost_date_time-mt-static
ADD_LIBRARY(boost_date_time-mt-static STATIC IMPORTED)

# Create imported target boost_date_time-shared
ADD_LIBRARY(boost_date_time-shared SHARED IMPORTED)

# Create imported target boost_date_time-mt-shared
ADD_LIBRARY(boost_date_time-mt-shared SHARED IMPORTED)

# Create imported target boost_date_time-static-debug
ADD_LIBRARY(boost_date_time-static-debug STATIC IMPORTED)

# Create imported target boost_date_time-mt-static-debug
ADD_LIBRARY(boost_date_time-mt-static-debug STATIC IMPORTED)

# Create imported target boost_date_time-shared-debug
ADD_LIBRARY(boost_date_time-shared-debug SHARED IMPORTED)

# Create imported target boost_date_time-mt-shared-debug
ADD_LIBRARY(boost_date_time-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_thread-mt-static
ADD_LIBRARY(boost_thread-mt-static STATIC IMPORTED)

# Create imported target boost_thread-mt-shared
ADD_LIBRARY(boost_thread-mt-shared SHARED IMPORTED)

# Create imported target boost_thread-mt-static-debug
ADD_LIBRARY(boost_thread-mt-static-debug STATIC IMPORTED)

# Create imported target boost_thread-mt-shared-debug
ADD_LIBRARY(boost_thread-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_regex-shared
ADD_LIBRARY(boost_regex-shared SHARED IMPORTED)

# Create imported target boost_regex-mt-shared
ADD_LIBRARY(boost_regex-mt-shared SHARED IMPORTED)

# Create imported target boost_regex-shared-debug
ADD_LIBRARY(boost_regex-shared-debug SHARED IMPORTED)

# Create imported target boost_regex-mt-shared-debug
ADD_LIBRARY(boost_regex-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_serialization-static
ADD_LIBRARY(boost_serialization-static STATIC IMPORTED)

# Create imported target boost_serialization-mt-static
ADD_LIBRARY(boost_serialization-mt-static STATIC IMPORTED)

# Create imported target boost_serialization-shared
ADD_LIBRARY(boost_serialization-shared SHARED IMPORTED)

# Create imported target boost_serialization-mt-shared
ADD_LIBRARY(boost_serialization-mt-shared SHARED IMPORTED)

# Create imported target boost_serialization-static-debug
ADD_LIBRARY(boost_serialization-static-debug STATIC IMPORTED)

# Create imported target boost_serialization-mt-static-debug
ADD_LIBRARY(boost_serialization-mt-static-debug STATIC IMPORTED)

# Create imported target boost_serialization-shared-debug
ADD_LIBRARY(boost_serialization-shared-debug SHARED IMPORTED)

# Create imported target boost_serialization-mt-shared-debug
ADD_LIBRARY(boost_serialization-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_wserialization-static
ADD_LIBRARY(boost_wserialization-static STATIC IMPORTED)

# Create imported target boost_wserialization-mt-static
ADD_LIBRARY(boost_wserialization-mt-static STATIC IMPORTED)

# Create imported target boost_wserialization-shared
ADD_LIBRARY(boost_wserialization-shared SHARED IMPORTED)

# Create imported target boost_wserialization-mt-shared
ADD_LIBRARY(boost_wserialization-mt-shared SHARED IMPORTED)

# Create imported target boost_wserialization-static-debug
ADD_LIBRARY(boost_wserialization-static-debug STATIC IMPORTED)

# Create imported target boost_wserialization-mt-static-debug
ADD_LIBRARY(boost_wserialization-mt-static-debug STATIC IMPORTED)

# Create imported target boost_wserialization-shared-debug
ADD_LIBRARY(boost_wserialization-shared-debug SHARED IMPORTED)

# Create imported target boost_wserialization-mt-shared-debug
ADD_LIBRARY(boost_wserialization-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_graph-shared
ADD_LIBRARY(boost_graph-shared SHARED IMPORTED)

# Create imported target boost_graph-mt-shared
ADD_LIBRARY(boost_graph-mt-shared SHARED IMPORTED)

# Create imported target boost_graph-shared-debug
ADD_LIBRARY(boost_graph-shared-debug SHARED IMPORTED)

# Create imported target boost_graph-mt-shared-debug
ADD_LIBRARY(boost_graph-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_python-static
ADD_LIBRARY(boost_python-static STATIC IMPORTED)

# Create imported target boost_python-mt-static
ADD_LIBRARY(boost_python-mt-static STATIC IMPORTED)

# Create imported target boost_python-shared
ADD_LIBRARY(boost_python-shared SHARED IMPORTED)

# Create imported target boost_python-mt-shared
ADD_LIBRARY(boost_python-mt-shared SHARED IMPORTED)

# Create imported target boost_python-static-debug
ADD_LIBRARY(boost_python-static-debug STATIC IMPORTED)

# Create imported target boost_python-mt-static-debug
ADD_LIBRARY(boost_python-mt-static-debug STATIC IMPORTED)

# Create imported target boost_python-shared-debug
ADD_LIBRARY(boost_python-shared-debug SHARED IMPORTED)

# Create imported target boost_python-mt-shared-debug
ADD_LIBRARY(boost_python-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_system-static
ADD_LIBRARY(boost_system-static STATIC IMPORTED)

# Create imported target boost_system-mt-static
ADD_LIBRARY(boost_system-mt-static STATIC IMPORTED)

# Create imported target boost_system-shared
ADD_LIBRARY(boost_system-shared SHARED IMPORTED)

# Create imported target boost_system-mt-shared
ADD_LIBRARY(boost_system-mt-shared SHARED IMPORTED)

# Create imported target boost_system-static-debug
ADD_LIBRARY(boost_system-static-debug STATIC IMPORTED)

# Create imported target boost_system-mt-static-debug
ADD_LIBRARY(boost_system-mt-static-debug STATIC IMPORTED)

# Create imported target boost_system-shared-debug
ADD_LIBRARY(boost_system-shared-debug SHARED IMPORTED)

# Create imported target boost_system-mt-shared-debug
ADD_LIBRARY(boost_system-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_prg_exec_monitor-static
ADD_LIBRARY(boost_prg_exec_monitor-static STATIC IMPORTED)

# Create imported target boost_prg_exec_monitor-mt-static
ADD_LIBRARY(boost_prg_exec_monitor-mt-static STATIC IMPORTED)

# Create imported target boost_prg_exec_monitor-shared
ADD_LIBRARY(boost_prg_exec_monitor-shared SHARED IMPORTED)

# Create imported target boost_prg_exec_monitor-mt-shared
ADD_LIBRARY(boost_prg_exec_monitor-mt-shared SHARED IMPORTED)

# Create imported target boost_prg_exec_monitor-static-debug
ADD_LIBRARY(boost_prg_exec_monitor-static-debug STATIC IMPORTED)

# Create imported target boost_prg_exec_monitor-mt-static-debug
ADD_LIBRARY(boost_prg_exec_monitor-mt-static-debug STATIC IMPORTED)

# Create imported target boost_prg_exec_monitor-shared-debug
ADD_LIBRARY(boost_prg_exec_monitor-shared-debug SHARED IMPORTED)

# Create imported target boost_prg_exec_monitor-mt-shared-debug
ADD_LIBRARY(boost_prg_exec_monitor-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_test_exec_monitor-static
ADD_LIBRARY(boost_test_exec_monitor-static STATIC IMPORTED)

# Create imported target boost_test_exec_monitor-mt-static
ADD_LIBRARY(boost_test_exec_monitor-mt-static STATIC IMPORTED)

# Create imported target boost_test_exec_monitor-static-debug
ADD_LIBRARY(boost_test_exec_monitor-static-debug STATIC IMPORTED)

# Create imported target boost_test_exec_monitor-mt-static-debug
ADD_LIBRARY(boost_test_exec_monitor-mt-static-debug STATIC IMPORTED)

# Create imported target boost_unit_test_framework-static
ADD_LIBRARY(boost_unit_test_framework-static STATIC IMPORTED)

# Create imported target boost_unit_test_framework-mt-static
ADD_LIBRARY(boost_unit_test_framework-mt-static STATIC IMPORTED)

# Create imported target boost_unit_test_framework-shared
ADD_LIBRARY(boost_unit_test_framework-shared SHARED IMPORTED)

# Create imported target boost_unit_test_framework-mt-shared
ADD_LIBRARY(boost_unit_test_framework-mt-shared SHARED IMPORTED)

# Create imported target boost_unit_test_framework-static-debug
ADD_LIBRARY(boost_unit_test_framework-static-debug STATIC IMPORTED)

# Create imported target boost_unit_test_framework-mt-static-debug
ADD_LIBRARY(boost_unit_test_framework-mt-static-debug STATIC IMPORTED)

# Create imported target boost_unit_test_framework-shared-debug
ADD_LIBRARY(boost_unit_test_framework-shared-debug SHARED IMPORTED)

# Create imported target boost_unit_test_framework-mt-shared-debug
ADD_LIBRARY(boost_unit_test_framework-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_filesystem-static
ADD_LIBRARY(boost_filesystem-static STATIC IMPORTED)

# Create imported target boost_filesystem-mt-static
ADD_LIBRARY(boost_filesystem-mt-static STATIC IMPORTED)

# Create imported target boost_filesystem-shared
ADD_LIBRARY(boost_filesystem-shared SHARED IMPORTED)

# Create imported target boost_filesystem-mt-shared
ADD_LIBRARY(boost_filesystem-mt-shared SHARED IMPORTED)

# Create imported target boost_filesystem-static-debug
ADD_LIBRARY(boost_filesystem-static-debug STATIC IMPORTED)

# Create imported target boost_filesystem-mt-static-debug
ADD_LIBRARY(boost_filesystem-mt-static-debug STATIC IMPORTED)

# Create imported target boost_filesystem-shared-debug
ADD_LIBRARY(boost_filesystem-shared-debug SHARED IMPORTED)

# Create imported target boost_filesystem-mt-shared-debug
ADD_LIBRARY(boost_filesystem-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_iostreams-static
ADD_LIBRARY(boost_iostreams-static STATIC IMPORTED)

# Create imported target boost_iostreams-mt-static
ADD_LIBRARY(boost_iostreams-mt-static STATIC IMPORTED)

# Create imported target boost_iostreams-shared
ADD_LIBRARY(boost_iostreams-shared SHARED IMPORTED)

# Create imported target boost_iostreams-mt-shared
ADD_LIBRARY(boost_iostreams-mt-shared SHARED IMPORTED)

# Create imported target boost_iostreams-static-debug
ADD_LIBRARY(boost_iostreams-static-debug STATIC IMPORTED)

# Create imported target boost_iostreams-mt-static-debug
ADD_LIBRARY(boost_iostreams-mt-static-debug STATIC IMPORTED)

# Create imported target boost_iostreams-shared-debug
ADD_LIBRARY(boost_iostreams-shared-debug SHARED IMPORTED)

# Create imported target boost_iostreams-mt-shared-debug
ADD_LIBRARY(boost_iostreams-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_program_options-static
ADD_LIBRARY(boost_program_options-static STATIC IMPORTED)

# Create imported target boost_program_options-mt-static
ADD_LIBRARY(boost_program_options-mt-static STATIC IMPORTED)

# Create imported target boost_program_options-shared
ADD_LIBRARY(boost_program_options-shared SHARED IMPORTED)

# Create imported target boost_program_options-mt-shared
ADD_LIBRARY(boost_program_options-mt-shared SHARED IMPORTED)

# Create imported target boost_program_options-static-debug
ADD_LIBRARY(boost_program_options-static-debug STATIC IMPORTED)

# Create imported target boost_program_options-mt-static-debug
ADD_LIBRARY(boost_program_options-mt-static-debug STATIC IMPORTED)

# Create imported target boost_program_options-shared-debug
ADD_LIBRARY(boost_program_options-shared-debug SHARED IMPORTED)

# Create imported target boost_program_options-mt-shared-debug
ADD_LIBRARY(boost_program_options-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_signals-static
ADD_LIBRARY(boost_signals-static STATIC IMPORTED)

# Create imported target boost_signals-mt-static
ADD_LIBRARY(boost_signals-mt-static STATIC IMPORTED)

# Create imported target boost_signals-shared
ADD_LIBRARY(boost_signals-shared SHARED IMPORTED)

# Create imported target boost_signals-mt-shared
ADD_LIBRARY(boost_signals-mt-shared SHARED IMPORTED)

# Create imported target boost_signals-static-debug
ADD_LIBRARY(boost_signals-static-debug STATIC IMPORTED)

# Create imported target boost_signals-mt-static-debug
ADD_LIBRARY(boost_signals-mt-static-debug STATIC IMPORTED)

# Create imported target boost_signals-shared-debug
ADD_LIBRARY(boost_signals-shared-debug SHARED IMPORTED)

# Create imported target boost_signals-mt-shared-debug
ADD_LIBRARY(boost_signals-mt-shared-debug SHARED IMPORTED)

# Create imported target boost_wave-mt-static
ADD_LIBRARY(boost_wave-mt-static STATIC IMPORTED)

# Create imported target boost_wave-mt-shared
ADD_LIBRARY(boost_wave-mt-shared SHARED IMPORTED)

# Create imported target boost_wave-mt-static-debug
ADD_LIBRARY(boost_wave-mt-static-debug STATIC IMPORTED)

# Create imported target boost_wave-mt-shared-debug
ADD_LIBRARY(boost_wave-mt-shared-debug SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/Boost-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
